package com.common.generate.javacreate.test.dto;

import java.math.BigDecimal;
import java.util.Date;

public class GroupSettleOrderBillPO {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.Id
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.OrgId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Integer orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.SettleOrderId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Long settleOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.BusinessNo
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private String businessNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.OrderId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Long orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.OrderItemId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Long orderItemId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.OrderDate
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Date orderDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.OrderType
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Byte orderType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.SkuId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Long skuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.SkuName
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private String skuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.ProductSaleSpec
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private String productSaleSpec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.SaleSpecQuantity
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private BigDecimal saleSpecQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.SellUnit
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private String sellUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.OrderPrice
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private BigDecimal orderPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.OrderAmount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private BigDecimal orderAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.OriginalMinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private BigDecimal originalMinUnitTotalCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.MinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private BigDecimal minUnitTotalCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.SettleMinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private BigDecimal settleMinUnitTotalCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.ProductOwnerId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Long productOwnerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.CreateTime
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.CreateUserId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Integer createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Integer lastUpdateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_bill.ProductSpecId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	private Long productSpecId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.Id
	 * @return  the value of group_settle_order_bill.Id
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.Id
	 * @param id  the value for group_settle_order_bill.Id
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.OrgId
	 * @return  the value of group_settle_order_bill.OrgId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Integer getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.OrgId
	 * @param orgId  the value for group_settle_order_bill.OrgId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.SettleOrderId
	 * @return  the value of group_settle_order_bill.SettleOrderId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Long getSettleOrderId() {
		return settleOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.SettleOrderId
	 * @param settleOrderId  the value for group_settle_order_bill.SettleOrderId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setSettleOrderId(Long settleOrderId) {
		this.settleOrderId = settleOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.BusinessNo
	 * @return  the value of group_settle_order_bill.BusinessNo
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public String getBusinessNo() {
		return businessNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.BusinessNo
	 * @param businessNo  the value for group_settle_order_bill.BusinessNo
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setBusinessNo(String businessNo) {
		this.businessNo = businessNo == null ? null : businessNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.OrderId
	 * @return  the value of group_settle_order_bill.OrderId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Long getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.OrderId
	 * @param orderId  the value for group_settle_order_bill.OrderId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setOrderId(Long orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.OrderItemId
	 * @return  the value of group_settle_order_bill.OrderItemId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Long getOrderItemId() {
		return orderItemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.OrderItemId
	 * @param orderItemId  the value for group_settle_order_bill.OrderItemId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setOrderItemId(Long orderItemId) {
		this.orderItemId = orderItemId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.OrderDate
	 * @return  the value of group_settle_order_bill.OrderDate
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Date getOrderDate() {
		return orderDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.OrderDate
	 * @param orderDate  the value for group_settle_order_bill.OrderDate
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.OrderType
	 * @return  the value of group_settle_order_bill.OrderType
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Byte getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.OrderType
	 * @param orderType  the value for group_settle_order_bill.OrderType
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setOrderType(Byte orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.SkuId
	 * @return  the value of group_settle_order_bill.SkuId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Long getSkuId() {
		return skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.SkuId
	 * @param skuId  the value for group_settle_order_bill.SkuId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setSkuId(Long skuId) {
		this.skuId = skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.SkuName
	 * @return  the value of group_settle_order_bill.SkuName
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public String getSkuName() {
		return skuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.SkuName
	 * @param skuName  the value for group_settle_order_bill.SkuName
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setSkuName(String skuName) {
		this.skuName = skuName == null ? null : skuName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.ProductSaleSpec
	 * @return  the value of group_settle_order_bill.ProductSaleSpec
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public String getProductSaleSpec() {
		return productSaleSpec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.ProductSaleSpec
	 * @param productSaleSpec  the value for group_settle_order_bill.ProductSaleSpec
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setProductSaleSpec(String productSaleSpec) {
		this.productSaleSpec = productSaleSpec == null ? null : productSaleSpec.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.SaleSpecQuantity
	 * @return  the value of group_settle_order_bill.SaleSpecQuantity
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public BigDecimal getSaleSpecQuantity() {
		return saleSpecQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.SaleSpecQuantity
	 * @param saleSpecQuantity  the value for group_settle_order_bill.SaleSpecQuantity
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setSaleSpecQuantity(BigDecimal saleSpecQuantity) {
		this.saleSpecQuantity = saleSpecQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.SellUnit
	 * @return  the value of group_settle_order_bill.SellUnit
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public String getSellUnit() {
		return sellUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.SellUnit
	 * @param sellUnit  the value for group_settle_order_bill.SellUnit
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setSellUnit(String sellUnit) {
		this.sellUnit = sellUnit == null ? null : sellUnit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.OrderPrice
	 * @return  the value of group_settle_order_bill.OrderPrice
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public BigDecimal getOrderPrice() {
		return orderPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.OrderPrice
	 * @param orderPrice  the value for group_settle_order_bill.OrderPrice
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setOrderPrice(BigDecimal orderPrice) {
		this.orderPrice = orderPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.OrderAmount
	 * @return  the value of group_settle_order_bill.OrderAmount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public BigDecimal getOrderAmount() {
		return orderAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.OrderAmount
	 * @param orderAmount  the value for group_settle_order_bill.OrderAmount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setOrderAmount(BigDecimal orderAmount) {
		this.orderAmount = orderAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.OriginalMinUnitTotalCount
	 * @return  the value of group_settle_order_bill.OriginalMinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public BigDecimal getOriginalMinUnitTotalCount() {
		return originalMinUnitTotalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.OriginalMinUnitTotalCount
	 * @param originalMinUnitTotalCount  the value for group_settle_order_bill.OriginalMinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setOriginalMinUnitTotalCount(BigDecimal originalMinUnitTotalCount) {
		this.originalMinUnitTotalCount = originalMinUnitTotalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.MinUnitTotalCount
	 * @return  the value of group_settle_order_bill.MinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public BigDecimal getMinUnitTotalCount() {
		return minUnitTotalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.MinUnitTotalCount
	 * @param minUnitTotalCount  the value for group_settle_order_bill.MinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setMinUnitTotalCount(BigDecimal minUnitTotalCount) {
		this.minUnitTotalCount = minUnitTotalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.SettleMinUnitTotalCount
	 * @return  the value of group_settle_order_bill.SettleMinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public BigDecimal getSettleMinUnitTotalCount() {
		return settleMinUnitTotalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.SettleMinUnitTotalCount
	 * @param settleMinUnitTotalCount  the value for group_settle_order_bill.SettleMinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setSettleMinUnitTotalCount(BigDecimal settleMinUnitTotalCount) {
		this.settleMinUnitTotalCount = settleMinUnitTotalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.ProductOwnerId
	 * @return  the value of group_settle_order_bill.ProductOwnerId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Long getProductOwnerId() {
		return productOwnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.ProductOwnerId
	 * @param productOwnerId  the value for group_settle_order_bill.ProductOwnerId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setProductOwnerId(Long productOwnerId) {
		this.productOwnerId = productOwnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.CreateTime
	 * @return  the value of group_settle_order_bill.CreateTime
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.CreateTime
	 * @param createTime  the value for group_settle_order_bill.CreateTime
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.CreateUserId
	 * @return  the value of group_settle_order_bill.CreateUserId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.CreateUserId
	 * @param createUserId  the value for group_settle_order_bill.CreateUserId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.LastUpdateTime
	 * @return  the value of group_settle_order_bill.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.LastUpdateTime
	 * @param lastUpdateTime  the value for group_settle_order_bill.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.LastUpdateUserId
	 * @return  the value of group_settle_order_bill.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Integer getLastUpdateUserId() {
		return lastUpdateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.LastUpdateUserId
	 * @param lastUpdateUserId  the value for group_settle_order_bill.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setLastUpdateUserId(Integer lastUpdateUserId) {
		this.lastUpdateUserId = lastUpdateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill.ProductSpecId
	 * @return  the value of group_settle_order_bill.ProductSpecId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public Long getProductSpecId() {
		return productSpecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill.ProductSpecId
	 * @param productSpecId  the value for group_settle_order_bill.ProductSpecId
	 * @mbg.generated  Wed Apr 21 11:36:16 CST 2021
	 */
	public void setProductSpecId(Long productSpecId) {
		this.productSpecId = productSpecId;
	}
}