package com.common.generate.javacreate.test.dto;

import java.math.BigDecimal;
import java.util.Date;

public class GroupSettleOrderSkuItemPO {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.Id
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.OrgId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Integer orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.SettleOrderId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Long settleOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.SaleDate
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Date saleDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.AccountDate
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Date accountDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.SettleDate
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Date settleDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.SkuId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Long skuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.SkuSettleType
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Byte skuSettleType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.ChannelNo
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Integer channelNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.ChannelCity
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private String channelCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.ChannelSkuName
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private String channelSkuName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.ProductSaleSpec
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private String productSaleSpec;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.SaleSpecQuantity
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private BigDecimal saleSpecQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.SalePrice
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private BigDecimal salePrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.SaleAmount
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private BigDecimal saleAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.MinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private BigDecimal minUnitTotalCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.CreateTime
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.CreateUserId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Integer createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Integer lastUpdateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.SellUnit
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private String sellUnit;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.ProductSpecId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Long productSpecId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku_item.ProductOwnerId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	private Long productOwnerId;

	/**
	 * 成本价
	 */
	private BigDecimal defaultCostPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.Id
	 * @return  the value of group_settle_order_sku_item.Id
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.Id
	 * @param id  the value for group_settle_order_sku_item.Id
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.OrgId
	 * @return  the value of group_settle_order_sku_item.OrgId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Integer getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.OrgId
	 * @param orgId  the value for group_settle_order_sku_item.OrgId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.SettleOrderId
	 * @return  the value of group_settle_order_sku_item.SettleOrderId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Long getSettleOrderId() {
		return settleOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.SettleOrderId
	 * @param settleOrderId  the value for group_settle_order_sku_item.SettleOrderId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setSettleOrderId(Long settleOrderId) {
		this.settleOrderId = settleOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.SaleDate
	 * @return  the value of group_settle_order_sku_item.SaleDate
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Date getSaleDate() {
		return saleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.SaleDate
	 * @param saleDate  the value for group_settle_order_sku_item.SaleDate
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setSaleDate(Date saleDate) {
		this.saleDate = saleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.AccountDate
	 * @return  the value of group_settle_order_sku_item.AccountDate
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Date getAccountDate() {
		return accountDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.AccountDate
	 * @param accountDate  the value for group_settle_order_sku_item.AccountDate
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setAccountDate(Date accountDate) {
		this.accountDate = accountDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.SettleDate
	 * @return  the value of group_settle_order_sku_item.SettleDate
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Date getSettleDate() {
		return settleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.SettleDate
	 * @param settleDate  the value for group_settle_order_sku_item.SettleDate
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setSettleDate(Date settleDate) {
		this.settleDate = settleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.SkuId
	 * @return  the value of group_settle_order_sku_item.SkuId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Long getSkuId() {
		return skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.SkuId
	 * @param skuId  the value for group_settle_order_sku_item.SkuId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setSkuId(Long skuId) {
		this.skuId = skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.SkuSettleType
	 * @return  the value of group_settle_order_sku_item.SkuSettleType
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Byte getSkuSettleType() {
		return skuSettleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.SkuSettleType
	 * @param skuSettleType  the value for group_settle_order_sku_item.SkuSettleType
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setSkuSettleType(Byte skuSettleType) {
		this.skuSettleType = skuSettleType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.ChannelNo
	 * @return  the value of group_settle_order_sku_item.ChannelNo
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Integer getChannelNo() {
		return channelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.ChannelNo
	 * @param channelNo  the value for group_settle_order_sku_item.ChannelNo
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setChannelNo(Integer channelNo) {
		this.channelNo = channelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.ChannelCity
	 * @return  the value of group_settle_order_sku_item.ChannelCity
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public String getChannelCity() {
		return channelCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.ChannelCity
	 * @param channelCity  the value for group_settle_order_sku_item.ChannelCity
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setChannelCity(String channelCity) {
		this.channelCity = channelCity == null ? null : channelCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.ChannelSkuName
	 * @return  the value of group_settle_order_sku_item.ChannelSkuName
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public String getChannelSkuName() {
		return channelSkuName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.ChannelSkuName
	 * @param channelSkuName  the value for group_settle_order_sku_item.ChannelSkuName
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setChannelSkuName(String channelSkuName) {
		this.channelSkuName = channelSkuName == null ? null : channelSkuName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.ProductSaleSpec
	 * @return  the value of group_settle_order_sku_item.ProductSaleSpec
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public String getProductSaleSpec() {
		return productSaleSpec;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.ProductSaleSpec
	 * @param productSaleSpec  the value for group_settle_order_sku_item.ProductSaleSpec
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setProductSaleSpec(String productSaleSpec) {
		this.productSaleSpec = productSaleSpec == null ? null : productSaleSpec.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.SaleSpecQuantity
	 * @return  the value of group_settle_order_sku_item.SaleSpecQuantity
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public BigDecimal getSaleSpecQuantity() {
		return saleSpecQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.SaleSpecQuantity
	 * @param saleSpecQuantity  the value for group_settle_order_sku_item.SaleSpecQuantity
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setSaleSpecQuantity(BigDecimal saleSpecQuantity) {
		this.saleSpecQuantity = saleSpecQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.SalePrice
	 * @return  the value of group_settle_order_sku_item.SalePrice
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public BigDecimal getSalePrice() {
		return salePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.SalePrice
	 * @param salePrice  the value for group_settle_order_sku_item.SalePrice
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setSalePrice(BigDecimal salePrice) {
		this.salePrice = salePrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.SaleAmount
	 * @return  the value of group_settle_order_sku_item.SaleAmount
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public BigDecimal getSaleAmount() {
		return saleAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.SaleAmount
	 * @param saleAmount  the value for group_settle_order_sku_item.SaleAmount
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setSaleAmount(BigDecimal saleAmount) {
		this.saleAmount = saleAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.MinUnitTotalCount
	 * @return  the value of group_settle_order_sku_item.MinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public BigDecimal getMinUnitTotalCount() {
		return minUnitTotalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.MinUnitTotalCount
	 * @param minUnitTotalCount  the value for group_settle_order_sku_item.MinUnitTotalCount
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setMinUnitTotalCount(BigDecimal minUnitTotalCount) {
		this.minUnitTotalCount = minUnitTotalCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.CreateTime
	 * @return  the value of group_settle_order_sku_item.CreateTime
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.CreateTime
	 * @param createTime  the value for group_settle_order_sku_item.CreateTime
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.CreateUserId
	 * @return  the value of group_settle_order_sku_item.CreateUserId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.CreateUserId
	 * @param createUserId  the value for group_settle_order_sku_item.CreateUserId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.LastUpdateTime
	 * @return  the value of group_settle_order_sku_item.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.LastUpdateTime
	 * @param lastUpdateTime  the value for group_settle_order_sku_item.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.LastUpdateUserId
	 * @return  the value of group_settle_order_sku_item.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Integer getLastUpdateUserId() {
		return lastUpdateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.LastUpdateUserId
	 * @param lastUpdateUserId  the value for group_settle_order_sku_item.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setLastUpdateUserId(Integer lastUpdateUserId) {
		this.lastUpdateUserId = lastUpdateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.SellUnit
	 * @return  the value of group_settle_order_sku_item.SellUnit
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public String getSellUnit() {
		return sellUnit;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.SellUnit
	 * @param sellUnit  the value for group_settle_order_sku_item.SellUnit
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setSellUnit(String sellUnit) {
		this.sellUnit = sellUnit == null ? null : sellUnit.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.ProductSpecId
	 * @return  the value of group_settle_order_sku_item.ProductSpecId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Long getProductSpecId() {
		return productSpecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.ProductSpecId
	 * @param productSpecId  the value for group_settle_order_sku_item.ProductSpecId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setProductSpecId(Long productSpecId) {
		this.productSpecId = productSpecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku_item.ProductOwnerId
	 * @return  the value of group_settle_order_sku_item.ProductOwnerId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public Long getProductOwnerId() {
		return productOwnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku_item.ProductOwnerId
	 * @param productOwnerId  the value for group_settle_order_sku_item.ProductOwnerId
	 * @mbg.generated  Wed Apr 21 10:49:15 CST 2021
	 */
	public void setProductOwnerId(Long productOwnerId) {
		this.productOwnerId = productOwnerId;
	}

	public BigDecimal getDefaultCostPrice() {
		return defaultCostPrice;
	}

	public void setDefaultCostPrice(BigDecimal defaultCostPrice) {
		this.defaultCostPrice = defaultCostPrice;
	}
}