package com.common.generate.javacreate.test.dto;

import java.math.BigDecimal;
import java.util.Date;

public class GroupSettleOrderSkuPO {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.Id
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.OrgId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Integer orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SkuId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Long skuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SettleOrderId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Long settleOrderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SaleDate
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Date saleDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.AccountDate
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Date accountDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SettleDate
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Date settleDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SaleWarehouseId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Integer saleWarehouseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.ChannelNo
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Integer channelNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.ChannelCity
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private String channelCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SaleDeliverPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal saleDeliverPackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SaleDeliverUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal saleDeliverUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.DeliverPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal deliverPackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.DeliverUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal deliverUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.TransformPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal transformPackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.TransformUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal transformUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SaleStorePackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal saleStorePackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SaleStoreUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal saleStoreUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.StorePackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal storePackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.StoreUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal storeUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.CancelStorePackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal cancelStorePackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.CancelStoreUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal cancelStoreUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SettleDiffPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal settleDiffPackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SettleDiffUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal settleDiffUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SaleSpecQuantity
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal saleSpecQuantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SettleAmount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private BigDecimal settleAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.SettleState
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Byte settleState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.CreateTime
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.CreateUserId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Integer createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Integer lastUpdateUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.ProductSpecId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Long productSpecId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order_sku.ProductOwnerId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	private Long productOwnerId;

	/**
	 * 成本价
	 */
	private BigDecimal defaultCostPrice;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.Id
	 * @return  the value of group_settle_order_sku.Id
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.Id
	 * @param id  the value for group_settle_order_sku.Id
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.OrgId
	 * @return  the value of group_settle_order_sku.OrgId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Integer getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.OrgId
	 * @param orgId  the value for group_settle_order_sku.OrgId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SkuId
	 * @return  the value of group_settle_order_sku.SkuId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Long getSkuId() {
		return skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SkuId
	 * @param skuId  the value for group_settle_order_sku.SkuId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSkuId(Long skuId) {
		this.skuId = skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SettleOrderId
	 * @return  the value of group_settle_order_sku.SettleOrderId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Long getSettleOrderId() {
		return settleOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SettleOrderId
	 * @param settleOrderId  the value for group_settle_order_sku.SettleOrderId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSettleOrderId(Long settleOrderId) {
		this.settleOrderId = settleOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SaleDate
	 * @return  the value of group_settle_order_sku.SaleDate
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Date getSaleDate() {
		return saleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SaleDate
	 * @param saleDate  the value for group_settle_order_sku.SaleDate
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSaleDate(Date saleDate) {
		this.saleDate = saleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.AccountDate
	 * @return  the value of group_settle_order_sku.AccountDate
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Date getAccountDate() {
		return accountDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.AccountDate
	 * @param accountDate  the value for group_settle_order_sku.AccountDate
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setAccountDate(Date accountDate) {
		this.accountDate = accountDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SettleDate
	 * @return  the value of group_settle_order_sku.SettleDate
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Date getSettleDate() {
		return settleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SettleDate
	 * @param settleDate  the value for group_settle_order_sku.SettleDate
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSettleDate(Date settleDate) {
		this.settleDate = settleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SaleWarehouseId
	 * @return  the value of group_settle_order_sku.SaleWarehouseId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Integer getSaleWarehouseId() {
		return saleWarehouseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SaleWarehouseId
	 * @param saleWarehouseId  the value for group_settle_order_sku.SaleWarehouseId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSaleWarehouseId(Integer saleWarehouseId) {
		this.saleWarehouseId = saleWarehouseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.ChannelNo
	 * @return  the value of group_settle_order_sku.ChannelNo
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Integer getChannelNo() {
		return channelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.ChannelNo
	 * @param channelNo  the value for group_settle_order_sku.ChannelNo
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setChannelNo(Integer channelNo) {
		this.channelNo = channelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.ChannelCity
	 * @return  the value of group_settle_order_sku.ChannelCity
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public String getChannelCity() {
		return channelCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.ChannelCity
	 * @param channelCity  the value for group_settle_order_sku.ChannelCity
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setChannelCity(String channelCity) {
		this.channelCity = channelCity == null ? null : channelCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SaleDeliverPackageCount
	 * @return  the value of group_settle_order_sku.SaleDeliverPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getSaleDeliverPackageCount() {
		return saleDeliverPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SaleDeliverPackageCount
	 * @param saleDeliverPackageCount  the value for group_settle_order_sku.SaleDeliverPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSaleDeliverPackageCount(BigDecimal saleDeliverPackageCount) {
		this.saleDeliverPackageCount = saleDeliverPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SaleDeliverUnitCount
	 * @return  the value of group_settle_order_sku.SaleDeliverUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getSaleDeliverUnitCount() {
		return saleDeliverUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SaleDeliverUnitCount
	 * @param saleDeliverUnitCount  the value for group_settle_order_sku.SaleDeliverUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSaleDeliverUnitCount(BigDecimal saleDeliverUnitCount) {
		this.saleDeliverUnitCount = saleDeliverUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.DeliverPackageCount
	 * @return  the value of group_settle_order_sku.DeliverPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getDeliverPackageCount() {
		return deliverPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.DeliverPackageCount
	 * @param deliverPackageCount  the value for group_settle_order_sku.DeliverPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setDeliverPackageCount(BigDecimal deliverPackageCount) {
		this.deliverPackageCount = deliverPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.DeliverUnitCount
	 * @return  the value of group_settle_order_sku.DeliverUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getDeliverUnitCount() {
		return deliverUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.DeliverUnitCount
	 * @param deliverUnitCount  the value for group_settle_order_sku.DeliverUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setDeliverUnitCount(BigDecimal deliverUnitCount) {
		this.deliverUnitCount = deliverUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.TransformPackageCount
	 * @return  the value of group_settle_order_sku.TransformPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getTransformPackageCount() {
		return transformPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.TransformPackageCount
	 * @param transformPackageCount  the value for group_settle_order_sku.TransformPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setTransformPackageCount(BigDecimal transformPackageCount) {
		this.transformPackageCount = transformPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.TransformUnitCount
	 * @return  the value of group_settle_order_sku.TransformUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getTransformUnitCount() {
		return transformUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.TransformUnitCount
	 * @param transformUnitCount  the value for group_settle_order_sku.TransformUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setTransformUnitCount(BigDecimal transformUnitCount) {
		this.transformUnitCount = transformUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SaleStorePackageCount
	 * @return  the value of group_settle_order_sku.SaleStorePackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getSaleStorePackageCount() {
		return saleStorePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SaleStorePackageCount
	 * @param saleStorePackageCount  the value for group_settle_order_sku.SaleStorePackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSaleStorePackageCount(BigDecimal saleStorePackageCount) {
		this.saleStorePackageCount = saleStorePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SaleStoreUnitCount
	 * @return  the value of group_settle_order_sku.SaleStoreUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getSaleStoreUnitCount() {
		return saleStoreUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SaleStoreUnitCount
	 * @param saleStoreUnitCount  the value for group_settle_order_sku.SaleStoreUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSaleStoreUnitCount(BigDecimal saleStoreUnitCount) {
		this.saleStoreUnitCount = saleStoreUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.StorePackageCount
	 * @return  the value of group_settle_order_sku.StorePackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getStorePackageCount() {
		return storePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.StorePackageCount
	 * @param storePackageCount  the value for group_settle_order_sku.StorePackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setStorePackageCount(BigDecimal storePackageCount) {
		this.storePackageCount = storePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.StoreUnitCount
	 * @return  the value of group_settle_order_sku.StoreUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getStoreUnitCount() {
		return storeUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.StoreUnitCount
	 * @param storeUnitCount  the value for group_settle_order_sku.StoreUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setStoreUnitCount(BigDecimal storeUnitCount) {
		this.storeUnitCount = storeUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.CancelStorePackageCount
	 * @return  the value of group_settle_order_sku.CancelStorePackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getCancelStorePackageCount() {
		return cancelStorePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.CancelStorePackageCount
	 * @param cancelStorePackageCount  the value for group_settle_order_sku.CancelStorePackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setCancelStorePackageCount(BigDecimal cancelStorePackageCount) {
		this.cancelStorePackageCount = cancelStorePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.CancelStoreUnitCount
	 * @return  the value of group_settle_order_sku.CancelStoreUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getCancelStoreUnitCount() {
		return cancelStoreUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.CancelStoreUnitCount
	 * @param cancelStoreUnitCount  the value for group_settle_order_sku.CancelStoreUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setCancelStoreUnitCount(BigDecimal cancelStoreUnitCount) {
		this.cancelStoreUnitCount = cancelStoreUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SettleDiffPackageCount
	 * @return  the value of group_settle_order_sku.SettleDiffPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getSettleDiffPackageCount() {
		return settleDiffPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SettleDiffPackageCount
	 * @param settleDiffPackageCount  the value for group_settle_order_sku.SettleDiffPackageCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSettleDiffPackageCount(BigDecimal settleDiffPackageCount) {
		this.settleDiffPackageCount = settleDiffPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SettleDiffUnitCount
	 * @return  the value of group_settle_order_sku.SettleDiffUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getSettleDiffUnitCount() {
		return settleDiffUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SettleDiffUnitCount
	 * @param settleDiffUnitCount  the value for group_settle_order_sku.SettleDiffUnitCount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSettleDiffUnitCount(BigDecimal settleDiffUnitCount) {
		this.settleDiffUnitCount = settleDiffUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SaleSpecQuantity
	 * @return  the value of group_settle_order_sku.SaleSpecQuantity
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getSaleSpecQuantity() {
		return saleSpecQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SaleSpecQuantity
	 * @param saleSpecQuantity  the value for group_settle_order_sku.SaleSpecQuantity
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSaleSpecQuantity(BigDecimal saleSpecQuantity) {
		this.saleSpecQuantity = saleSpecQuantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SettleAmount
	 * @return  the value of group_settle_order_sku.SettleAmount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public BigDecimal getSettleAmount() {
		return settleAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SettleAmount
	 * @param settleAmount  the value for group_settle_order_sku.SettleAmount
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSettleAmount(BigDecimal settleAmount) {
		this.settleAmount = settleAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.SettleState
	 * @return  the value of group_settle_order_sku.SettleState
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Byte getSettleState() {
		return settleState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.SettleState
	 * @param settleState  the value for group_settle_order_sku.SettleState
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setSettleState(Byte settleState) {
		this.settleState = settleState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.CreateTime
	 * @return  the value of group_settle_order_sku.CreateTime
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.CreateTime
	 * @param createTime  the value for group_settle_order_sku.CreateTime
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.CreateUserId
	 * @return  the value of group_settle_order_sku.CreateUserId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.CreateUserId
	 * @param createUserId  the value for group_settle_order_sku.CreateUserId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.LastUpdateTime
	 * @return  the value of group_settle_order_sku.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.LastUpdateTime
	 * @param lastUpdateTime  the value for group_settle_order_sku.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.LastUpdateUserId
	 * @return  the value of group_settle_order_sku.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Integer getLastUpdateUserId() {
		return lastUpdateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.LastUpdateUserId
	 * @param lastUpdateUserId  the value for group_settle_order_sku.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setLastUpdateUserId(Integer lastUpdateUserId) {
		this.lastUpdateUserId = lastUpdateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.ProductSpecId
	 * @return  the value of group_settle_order_sku.ProductSpecId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Long getProductSpecId() {
		return productSpecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.ProductSpecId
	 * @param productSpecId  the value for group_settle_order_sku.ProductSpecId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setProductSpecId(Long productSpecId) {
		this.productSpecId = productSpecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_sku.ProductOwnerId
	 * @return  the value of group_settle_order_sku.ProductOwnerId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public Long getProductOwnerId() {
		return productOwnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_sku.ProductOwnerId
	 * @param productOwnerId  the value for group_settle_order_sku.ProductOwnerId
	 * @mbg.generated  Wed Apr 21 10:20:00 CST 2021
	 */
	public void setProductOwnerId(Long productOwnerId) {
		this.productOwnerId = productOwnerId;
	}

	public BigDecimal getDefaultCostPrice() {
		return defaultCostPrice;
	}

	public void setDefaultCostPrice(BigDecimal defaultCostPrice) {
		this.defaultCostPrice = defaultCostPrice;
	}
}