package com.common.generate.javacreate.test.dto;

import java.math.BigDecimal;
import java.util.Date;

public class GroupSettleOrderPO {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.Id
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SettleNo
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private String settleNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.OrgId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Integer orgId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SaleDate
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Date saleDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.AccountDate
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Date accountDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SettleDate
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Date settleDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SaleWarehouseId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Integer saleWarehouseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.ChannelNo
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Integer channelNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.ChannelCity
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private String channelCity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SaleDeliverPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal saleDeliverPackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SaleDeliverUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal saleDeliverUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.DeliverPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal deliverPackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.DeliverUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal deliverUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.TransformPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal transformPackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.TransformUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal transformUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SaleStorePackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal saleStorePackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SaleStoreUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal saleStoreUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.StorePackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal storePackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.StoreUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal storeUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.CancelStorePackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal cancelStorePackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.CancelStoreUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal cancelStoreUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SettleDiffPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal settleDiffPackageCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SettleDiffUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal settleDiffUnitCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SkuCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Integer skuCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SettleAmount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private BigDecimal settleAmount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.SettleState
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Byte settleState;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.Isdelete
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Byte isdelete;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.CreateTime
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.CreateUserId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Integer createUserId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.LastUpdateTime
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Date lastUpdateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column group_settle_order.LastUpdateUserId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	private Integer lastUpdateUserId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.Id
	 * @return  the value of group_settle_order.Id
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.Id
	 * @param id  the value for group_settle_order.Id
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SettleNo
	 * @return  the value of group_settle_order.SettleNo
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public String getSettleNo() {
		return settleNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SettleNo
	 * @param settleNo  the value for group_settle_order.SettleNo
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSettleNo(String settleNo) {
		this.settleNo = settleNo == null ? null : settleNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.OrgId
	 * @return  the value of group_settle_order.OrgId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Integer getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.OrgId
	 * @param orgId  the value for group_settle_order.OrgId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SaleDate
	 * @return  the value of group_settle_order.SaleDate
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Date getSaleDate() {
		return saleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SaleDate
	 * @param saleDate  the value for group_settle_order.SaleDate
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSaleDate(Date saleDate) {
		this.saleDate = saleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.AccountDate
	 * @return  the value of group_settle_order.AccountDate
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Date getAccountDate() {
		return accountDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.AccountDate
	 * @param accountDate  the value for group_settle_order.AccountDate
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setAccountDate(Date accountDate) {
		this.accountDate = accountDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SettleDate
	 * @return  the value of group_settle_order.SettleDate
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Date getSettleDate() {
		return settleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SettleDate
	 * @param settleDate  the value for group_settle_order.SettleDate
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSettleDate(Date settleDate) {
		this.settleDate = settleDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SaleWarehouseId
	 * @return  the value of group_settle_order.SaleWarehouseId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Integer getSaleWarehouseId() {
		return saleWarehouseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SaleWarehouseId
	 * @param saleWarehouseId  the value for group_settle_order.SaleWarehouseId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSaleWarehouseId(Integer saleWarehouseId) {
		this.saleWarehouseId = saleWarehouseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.ChannelNo
	 * @return  the value of group_settle_order.ChannelNo
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Integer getChannelNo() {
		return channelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.ChannelNo
	 * @param channelNo  the value for group_settle_order.ChannelNo
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setChannelNo(Integer channelNo) {
		this.channelNo = channelNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.ChannelCity
	 * @return  the value of group_settle_order.ChannelCity
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public String getChannelCity() {
		return channelCity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.ChannelCity
	 * @param channelCity  the value for group_settle_order.ChannelCity
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setChannelCity(String channelCity) {
		this.channelCity = channelCity == null ? null : channelCity.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SaleDeliverPackageCount
	 * @return  the value of group_settle_order.SaleDeliverPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getSaleDeliverPackageCount() {
		return saleDeliverPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SaleDeliverPackageCount
	 * @param saleDeliverPackageCount  the value for group_settle_order.SaleDeliverPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSaleDeliverPackageCount(BigDecimal saleDeliverPackageCount) {
		this.saleDeliverPackageCount = saleDeliverPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SaleDeliverUnitCount
	 * @return  the value of group_settle_order.SaleDeliverUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getSaleDeliverUnitCount() {
		return saleDeliverUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SaleDeliverUnitCount
	 * @param saleDeliverUnitCount  the value for group_settle_order.SaleDeliverUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSaleDeliverUnitCount(BigDecimal saleDeliverUnitCount) {
		this.saleDeliverUnitCount = saleDeliverUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.DeliverPackageCount
	 * @return  the value of group_settle_order.DeliverPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getDeliverPackageCount() {
		return deliverPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.DeliverPackageCount
	 * @param deliverPackageCount  the value for group_settle_order.DeliverPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setDeliverPackageCount(BigDecimal deliverPackageCount) {
		this.deliverPackageCount = deliverPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.DeliverUnitCount
	 * @return  the value of group_settle_order.DeliverUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getDeliverUnitCount() {
		return deliverUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.DeliverUnitCount
	 * @param deliverUnitCount  the value for group_settle_order.DeliverUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setDeliverUnitCount(BigDecimal deliverUnitCount) {
		this.deliverUnitCount = deliverUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.TransformPackageCount
	 * @return  the value of group_settle_order.TransformPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getTransformPackageCount() {
		return transformPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.TransformPackageCount
	 * @param transformPackageCount  the value for group_settle_order.TransformPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setTransformPackageCount(BigDecimal transformPackageCount) {
		this.transformPackageCount = transformPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.TransformUnitCount
	 * @return  the value of group_settle_order.TransformUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getTransformUnitCount() {
		return transformUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.TransformUnitCount
	 * @param transformUnitCount  the value for group_settle_order.TransformUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setTransformUnitCount(BigDecimal transformUnitCount) {
		this.transformUnitCount = transformUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SaleStorePackageCount
	 * @return  the value of group_settle_order.SaleStorePackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getSaleStorePackageCount() {
		return saleStorePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SaleStorePackageCount
	 * @param saleStorePackageCount  the value for group_settle_order.SaleStorePackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSaleStorePackageCount(BigDecimal saleStorePackageCount) {
		this.saleStorePackageCount = saleStorePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SaleStoreUnitCount
	 * @return  the value of group_settle_order.SaleStoreUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getSaleStoreUnitCount() {
		return saleStoreUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SaleStoreUnitCount
	 * @param saleStoreUnitCount  the value for group_settle_order.SaleStoreUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSaleStoreUnitCount(BigDecimal saleStoreUnitCount) {
		this.saleStoreUnitCount = saleStoreUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.StorePackageCount
	 * @return  the value of group_settle_order.StorePackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getStorePackageCount() {
		return storePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.StorePackageCount
	 * @param storePackageCount  the value for group_settle_order.StorePackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setStorePackageCount(BigDecimal storePackageCount) {
		this.storePackageCount = storePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.StoreUnitCount
	 * @return  the value of group_settle_order.StoreUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getStoreUnitCount() {
		return storeUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.StoreUnitCount
	 * @param storeUnitCount  the value for group_settle_order.StoreUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setStoreUnitCount(BigDecimal storeUnitCount) {
		this.storeUnitCount = storeUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.CancelStorePackageCount
	 * @return  the value of group_settle_order.CancelStorePackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getCancelStorePackageCount() {
		return cancelStorePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.CancelStorePackageCount
	 * @param cancelStorePackageCount  the value for group_settle_order.CancelStorePackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setCancelStorePackageCount(BigDecimal cancelStorePackageCount) {
		this.cancelStorePackageCount = cancelStorePackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.CancelStoreUnitCount
	 * @return  the value of group_settle_order.CancelStoreUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getCancelStoreUnitCount() {
		return cancelStoreUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.CancelStoreUnitCount
	 * @param cancelStoreUnitCount  the value for group_settle_order.CancelStoreUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setCancelStoreUnitCount(BigDecimal cancelStoreUnitCount) {
		this.cancelStoreUnitCount = cancelStoreUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SettleDiffPackageCount
	 * @return  the value of group_settle_order.SettleDiffPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getSettleDiffPackageCount() {
		return settleDiffPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SettleDiffPackageCount
	 * @param settleDiffPackageCount  the value for group_settle_order.SettleDiffPackageCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSettleDiffPackageCount(BigDecimal settleDiffPackageCount) {
		this.settleDiffPackageCount = settleDiffPackageCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SettleDiffUnitCount
	 * @return  the value of group_settle_order.SettleDiffUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getSettleDiffUnitCount() {
		return settleDiffUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SettleDiffUnitCount
	 * @param settleDiffUnitCount  the value for group_settle_order.SettleDiffUnitCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSettleDiffUnitCount(BigDecimal settleDiffUnitCount) {
		this.settleDiffUnitCount = settleDiffUnitCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SkuCount
	 * @return  the value of group_settle_order.SkuCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Integer getSkuCount() {
		return skuCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SkuCount
	 * @param skuCount  the value for group_settle_order.SkuCount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSkuCount(Integer skuCount) {
		this.skuCount = skuCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SettleAmount
	 * @return  the value of group_settle_order.SettleAmount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public BigDecimal getSettleAmount() {
		return settleAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SettleAmount
	 * @param settleAmount  the value for group_settle_order.SettleAmount
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSettleAmount(BigDecimal settleAmount) {
		this.settleAmount = settleAmount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.SettleState
	 * @return  the value of group_settle_order.SettleState
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Byte getSettleState() {
		return settleState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.SettleState
	 * @param settleState  the value for group_settle_order.SettleState
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setSettleState(Byte settleState) {
		this.settleState = settleState;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.Isdelete
	 * @return  the value of group_settle_order.Isdelete
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Byte getIsdelete() {
		return isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.Isdelete
	 * @param isdelete  the value for group_settle_order.Isdelete
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setIsdelete(Byte isdelete) {
		this.isdelete = isdelete;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.CreateTime
	 * @return  the value of group_settle_order.CreateTime
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.CreateTime
	 * @param createTime  the value for group_settle_order.CreateTime
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.CreateUserId
	 * @return  the value of group_settle_order.CreateUserId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.CreateUserId
	 * @param createUserId  the value for group_settle_order.CreateUserId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.LastUpdateTime
	 * @return  the value of group_settle_order.LastUpdateTime
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.LastUpdateTime
	 * @param lastUpdateTime  the value for group_settle_order.LastUpdateTime
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order.LastUpdateUserId
	 * @return  the value of group_settle_order.LastUpdateUserId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public Integer getLastUpdateUserId() {
		return lastUpdateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order.LastUpdateUserId
	 * @param lastUpdateUserId  the value for group_settle_order.LastUpdateUserId
	 * @mbg.generated  Wed Apr 07 18:16:53 CST 2021
	 */
	public void setLastUpdateUserId(Integer lastUpdateUserId) {
		this.lastUpdateUserId = lastUpdateUserId;
	}
}