package com.common.generate.javacreate.test.erp;

import java.math.BigDecimal;
import java.util.Date;

public class GroupSettleOrderBillOwnerDTO {


	private Long id;

	private Integer orgId;

	private Long settleOrderId;

	private Long billId;

	private Byte orderType;

	private Long skuId;

	private Long dispatchSecProductOwnerId;

	private BigDecimal dispatchCount;

	private Date createTime;

	private Integer createUserId;

	private Date lastUpdateTime;

	private Integer lastUpdateUserId;

	private Long productSpecId;


	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.Id
	 * @param id  the value for group_settle_order_bill_owner.Id
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.OrgId
	 * @return  the value of group_settle_order_bill_owner.OrgId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Integer getOrgId() {
		return orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.OrgId
	 * @param orgId  the value for group_settle_order_bill_owner.OrgId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setOrgId(Integer orgId) {
		this.orgId = orgId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.SettleOrderId
	 * @return  the value of group_settle_order_bill_owner.SettleOrderId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Long getSettleOrderId() {
		return settleOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.SettleOrderId
	 * @param settleOrderId  the value for group_settle_order_bill_owner.SettleOrderId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setSettleOrderId(Long settleOrderId) {
		this.settleOrderId = settleOrderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.BillId
	 * @return  the value of group_settle_order_bill_owner.BillId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Long getBillId() {
		return billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.BillId
	 * @param billId  the value for group_settle_order_bill_owner.BillId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setBillId(Long billId) {
		this.billId = billId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.OrderType
	 * @return  the value of group_settle_order_bill_owner.OrderType
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Byte getOrderType() {
		return orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.OrderType
	 * @param orderType  the value for group_settle_order_bill_owner.OrderType
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setOrderType(Byte orderType) {
		this.orderType = orderType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.SkuId
	 * @return  the value of group_settle_order_bill_owner.SkuId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Long getSkuId() {
		return skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.SkuId
	 * @param skuId  the value for group_settle_order_bill_owner.SkuId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setSkuId(Long skuId) {
		this.skuId = skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.DispatchSecProductOwnerId
	 * @return  the value of group_settle_order_bill_owner.DispatchSecProductOwnerId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Long getDispatchSecProductOwnerId() {
		return dispatchSecProductOwnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.DispatchSecProductOwnerId
	 * @param dispatchSecProductOwnerId  the value for group_settle_order_bill_owner.DispatchSecProductOwnerId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setDispatchSecProductOwnerId(Long dispatchSecProductOwnerId) {
		this.dispatchSecProductOwnerId = dispatchSecProductOwnerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.DispatchCount
	 * @return  the value of group_settle_order_bill_owner.DispatchCount
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public BigDecimal getDispatchCount() {
		return dispatchCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.DispatchCount
	 * @param dispatchCount  the value for group_settle_order_bill_owner.DispatchCount
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setDispatchCount(BigDecimal dispatchCount) {
		this.dispatchCount = dispatchCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.CreateTime
	 * @return  the value of group_settle_order_bill_owner.CreateTime
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.CreateTime
	 * @param createTime  the value for group_settle_order_bill_owner.CreateTime
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.CreateUserId
	 * @return  the value of group_settle_order_bill_owner.CreateUserId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Integer getCreateUserId() {
		return createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.CreateUserId
	 * @param createUserId  the value for group_settle_order_bill_owner.CreateUserId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setCreateUserId(Integer createUserId) {
		this.createUserId = createUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.LastUpdateTime
	 * @return  the value of group_settle_order_bill_owner.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Date getLastUpdateTime() {
		return lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.LastUpdateTime
	 * @param lastUpdateTime  the value for group_settle_order_bill_owner.LastUpdateTime
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setLastUpdateTime(Date lastUpdateTime) {
		this.lastUpdateTime = lastUpdateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.LastUpdateUserId
	 * @return  the value of group_settle_order_bill_owner.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Integer getLastUpdateUserId() {
		return lastUpdateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.LastUpdateUserId
	 * @param lastUpdateUserId  the value for group_settle_order_bill_owner.LastUpdateUserId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setLastUpdateUserId(Integer lastUpdateUserId) {
		this.lastUpdateUserId = lastUpdateUserId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column group_settle_order_bill_owner.ProductSpecId
	 * @return  the value of group_settle_order_bill_owner.ProductSpecId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public Long getProductSpecId() {
		return productSpecId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column group_settle_order_bill_owner.ProductSpecId
	 * @param productSpecId  the value for group_settle_order_bill_owner.ProductSpecId
	 * @mbg.generated  Wed Apr 21 11:56:39 CST 2021
	 */
	public void setProductSpecId(Long productSpecId) {
		this.productSpecId = productSpecId;
	}
}